#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"

fail() {
  printf 'FAIL: %s\n' "$1" >&2
  exit 1
}

check_file() {
  local path="$1"
  [ -f "$ROOT/$path" ] || fail "missing file: $path"
}

check_pattern() {
  local pattern="$1"
  local path="$2"
  rg -n "$pattern" "$ROOT/$path" >/dev/null || fail "missing pattern in $path: $pattern"
}

check_absent_pattern() {
  local pattern="$1"
  if rg -n "$pattern" "$ROOT" >/dev/null; then
    rg -n "$pattern" "$ROOT" >&2
    fail "unexpected placeholder or drift marker"
  fi
}

required_files=(
  "README.md"
  "AGENTS.md"
  "partner/persona.md"
  "partner/operating-system.md"
  "partner/focus-risk-loop.md"
  "partner/loop-registry.md"
  "partner/project-map.md"
  "partner/research-backlog.md"
  "partner/evidence-index.md"
  "partner/decision-log.md"
  "partner/focus-radar.md"
  "partner/session-runbook.md"
  "partner/activation-guide.md"
  "partner/pilot-playbook.md"
  "partner/pilot-candidates.md"
  "partner/pilots/2026-06-07-agent-interaction-bridge-cold-start.md"
  "partner/pilots/2026-06-07-agent-interaction-bridge-presentation-rendering-checkpoint.md"
  "partner/pilots/2026-06-07-agent-interaction-bridge-pointer-adoption.md"
  "partner/pilots/2026-06-07-online-community-session-runtime-cold-start.md"
  "partner/pilots/2026-06-07-online-community-manual-acceptance-plan.md"
  "partner/session-ledger.md"
  "partner/loop-reports/2026-06-07-daily-radar.md"
  "partner/templates/research-loop-packet.md"
  "partner/templates/project-loop-packet.md"
  "partner/templates/thinking-loop-packet.md"
  "partner/templates/memory-candidate-packet.md"
  "partner/templates/reentry-risk-packet.md"
  "partner/templates/loop-report.md"
  "partner/templates/project-local-pointer.md"
  "partner/skills/problem-decomposer/SKILL.md"
  "scripts/verify-partner-workspace.sh"
  "scripts/context-snapshot.sh"
)

for file in "${required_files[@]}"; do
  check_file "$file"
done

check_absent_pattern "TB""D|TO""DO|待""补|以后""再说"

check_pattern "human-agent peer" "AGENTS.md"
check_pattern "alpha-partner" "README.md"
check_pattern "not a Codex application" "README.md"
check_pattern "current body and execution carrier" "README.md"
check_pattern "Alpha Partner" "AGENTS.md"
check_pattern "current body and carrier" "AGENTS.md"
check_pattern "co-founder" "AGENTS.md"
check_pattern "alphaX" "AGENTS.md"
check_pattern "共同研究执行" "AGENTS.md"
check_pattern "Spec Checkpoint" "AGENTS.md"
check_pattern "durable memory" "AGENTS.md"
check_pattern "loop-registry.md" "AGENTS.md"
check_pattern "loop-report.md" "AGENTS.md"
check_pattern "not an MCP server, application, or full knowledge base" "AGENTS.md"

check_pattern "Alpha Partner Persona" "partner/persona.md"
check_pattern "not a Codex app" "partner/persona.md"
check_pattern "Copilot-style executor" "partner/persona.md"
check_pattern "Research Loop" "partner/operating-system.md"
check_pattern "Project Loop" "partner/operating-system.md"
check_pattern "Thinking Loop" "partner/operating-system.md"
check_pattern "Memory Loop" "partner/operating-system.md"
check_pattern "Focus And Risk Loop" "partner/operating-system.md"
check_pattern "Focus And Risk Loop" "partner/focus-risk-loop.md"
check_pattern "attention fragmentation" "partner/focus-risk-loop.md"
check_pattern "false completion" "partner/focus-risk-loop.md"
check_pattern "Focus Move" "partner/focus-risk-loop.md"
check_pattern "Loop Registry" "partner/loop-registry.md"
check_pattern "loops protect attention" "partner/loop-registry.md"
check_pattern "read-only by default" "partner/loop-registry.md"
check_pattern "Observation Boundary" "partner/loop-registry.md"
check_pattern "Daily Focus Radar" "partner/loop-registry.md"
check_pattern "Source Drift Watch" "partner/loop-registry.md"
check_pattern "False Completion Watch" "partner/loop-registry.md"
check_pattern "PR/CI Watch" "partner/loop-registry.md"
check_pattern "Research Intake" "partner/loop-registry.md"
check_pattern "Proactive Nudge Experiment" "partner/loop-registry.md"
check_pattern "Upgrade Gate" "partner/loop-registry.md"
check_pattern "Focus Radar" "partner/focus-radar.md"
check_pattern "Portfolio P0" "partner/focus-radar.md"
check_pattern "False completion" "partner/focus-radar.md"
check_pattern "dirty WIP" "partner/focus-radar.md"
check_pattern "manual acceptance plan prepared" "partner/focus-radar.md"
check_pattern "Daily radar outcome" "partner/focus-radar.md"
check_pattern "alphaX nudge check" "partner/focus-radar.md"

check_pattern "Agent 化组织" "partner/project-map.md"
check_pattern "L0-L4" "partner/project-map.md"
check_pattern "Agent 知识治理闭环" "partner/project-map.md"
check_pattern "端侧 Agent 数据权限回收" "partner/project-map.md"

check_pattern "OpenAI Agents SDK" "partner/research-backlog.md"
check_pattern "Claude Code best practices" "partner/research-backlog.md"
check_pattern "Human-AI Collaboration" "partner/research-backlog.md"
check_pattern "Human-AI Synergy" "partner/research-backlog.md"
check_pattern "CMU SEI" "partner/research-backlog.md"
check_pattern "GitHub Copilot cloud agent docs as an execution-layer comparison" "partner/research-backlog.md"
check_pattern "Local-First Proactive Agents" "partner/research-backlog.md"

check_pattern "Workspace use" "partner/evidence-index.md"
check_pattern "contrast case" "partner/evidence-index.md"
check_pattern "端侧 Agent 数据权限回收" "partner/evidence-index.md"
check_pattern "session runbook" "partner/decision-log.md"
check_pattern "Agent-Native Activation" "partner/activation-guide.md"
check_pattern "Minimal Triggers" "partner/activation-guide.md"
check_pattern "Agent Responsibility After Trigger" "partner/activation-guide.md"
check_pattern "Context Snapshot Helper" "partner/activation-guide.md"
check_pattern "Sub-Agent Reference" "partner/activation-guide.md"
check_pattern "alphaX 介入一下" "partner/activation-guide.md"
check_pattern "alphaX 帮我恢复一下这个项目现场" "partner/activation-guide.md"
check_pattern "alphaX review 一下我现在几个项目的风险" "partner/activation-guide.md"
check_pattern "alphaX daily radar" "partner/activation-guide.md"
check_pattern "alphaX source drift check" "partner/activation-guide.md"
check_pattern "alphaX false completion check" "partner/activation-guide.md"
check_pattern "alphaX nudge check" "partner/activation-guide.md"
check_pattern "Proactive Nudge Boundary" "partner/activation-guide.md"
check_pattern "按 Codex Partner 方式推进" "partner/activation-guide.md"
check_pattern "context-snapshot.sh" "partner/session-runbook.md"
check_pattern "focus-risk-loop.md" "partner/session-runbook.md"
check_pattern "focus-radar.md" "partner/session-runbook.md"
check_pattern "loop-registry.md" "partner/session-runbook.md"
check_pattern "Likely Source Of Truth" "scripts/context-snapshot.sh"
check_pattern "Pilot Playbook" "partner/pilot-playbook.md"
check_pattern "Pilot Start Prompt" "partner/pilot-playbook.md"
check_pattern "Success Evidence" "partner/pilot-playbook.md"
check_pattern "Pilot Candidates" "partner/pilot-candidates.md"
check_pattern "Recommended First Pilot: agent-interaction-bridge" "partner/pilot-candidates.md"
check_pattern "alphaX 介入一下 /Users/lizhaohua/work/llm/agent-interaction-bridge" "partner/pilot-candidates.md"
check_pattern "Project-local pointer adopted" "partner/pilot-candidates.md"
check_pattern "online_community Session Runtime" "partner/pilot-candidates.md"
check_pattern "Read-only cold start completed" "partner/pilot-candidates.md"
check_pattern "agent-interaction-bridge Cold Start" "partner/pilots/2026-06-07-agent-interaction-bridge-cold-start.md"
check_pattern "architecture contract tests passed" "partner/pilots/2026-06-07-agent-interaction-bridge-cold-start.md"
check_pattern "Dynamic UI migration" "partner/pilots/2026-06-07-agent-interaction-bridge-cold-start.md"
check_pattern "presentation.rendering Focused Spec Checkpoint" "partner/pilots/2026-06-07-agent-interaction-bridge-presentation-rendering-checkpoint.md"
check_pattern "P0 主链路" "partner/pilots/2026-06-07-agent-interaction-bridge-presentation-rendering-checkpoint.md"
check_pattern "test suite passed: 72 files, 250 tests" "partner/pilots/2026-06-07-agent-interaction-bridge-presentation-rendering-checkpoint.md"
check_pattern "Move Dynamic UI heuristic ownership out of" "partner/pilots/2026-06-07-agent-interaction-bridge-presentation-rendering-checkpoint.md"
check_pattern "Project-Local Pointer Adoption" "partner/pilots/2026-06-07-agent-interaction-bridge-pointer-adoption.md"
check_pattern "detected the project-local Codex Partner pointer" "partner/pilots/2026-06-07-agent-interaction-bridge-pointer-adoption.md"
check_pattern "does not change project architecture" "partner/pilots/2026-06-07-agent-interaction-bridge-pointer-adoption.md"
check_pattern "online_community Session Runtime Cold Start" "partner/pilots/2026-06-07-online-community-session-runtime-cold-start.md"
check_pattern "manual acceptance is still the real next gate" "partner/pilots/2026-06-07-online-community-session-runtime-cold-start.md"
check_pattern "did not contain sample transcript lines" "partner/pilots/2026-06-07-online-community-session-runtime-cold-start.md"
check_pattern "online_community Manual Acceptance" "partner/pilots/2026-06-07-online-community-manual-acceptance-plan.md"
check_pattern "Do not commit transcript content" "partner/pilots/2026-06-07-online-community-manual-acceptance-plan.md"
check_pattern "Non-Sensitive Summary Shape" "partner/pilots/2026-06-07-online-community-manual-acceptance-plan.md"
check_pattern "manual_acceptance_status" "partner/pilots/2026-06-07-online-community-manual-acceptance-plan.md"
check_pattern "Session Ledger" "partner/session-ledger.md"
check_pattern "After every three new entries" "partner/session-ledger.md"
check_pattern "Latest review" "partner/session-ledger.md"
check_pattern "Second review" "partner/session-ledger.md"
check_pattern "two read-only real-project cold starts" "partner/session-ledger.md"
check_pattern "Partner Workspace Activation Redesign" "partner/session-ledger.md"
check_pattern "agent reconstructs context" "partner/session-ledger.md"
check_pattern "agent-interaction-bridge Cold Start Pilot" "partner/session-ledger.md"
check_pattern "presentation.rendering Focused Checkpoint" "partner/session-ledger.md"
check_pattern "online_community Session Runtime Cold Start" "partner/session-ledger.md"
check_pattern "Project-Local Pointer Adoption" "partner/session-ledger.md"
check_pattern "Focus And Risk Loop Added" "partner/session-ledger.md"
check_pattern "missed-risk review loop" "partner/session-ledger.md"
check_pattern "Focus Radar Created" "partner/session-ledger.md"
check_pattern "portfolio-level focus surface" "partner/session-ledger.md"
check_pattern "online_community Manual Acceptance Plan" "partner/session-ledger.md"
check_pattern "non-sensitive summary format" "partner/session-ledger.md"
check_pattern "Manual Loop Layer Added" "partner/session-ledger.md"
check_pattern "source drift" "partner/session-ledger.md"
check_pattern "proactive nudge" "partner/session-ledger.md"
check_pattern "Loop Packets" "partner/operating-system.md"
check_pattern "Manual Loop Layer" "partner/operating-system.md"
check_pattern "Loop Report: Daily Focus Radar" "partner/loop-reports/2026-06-07-daily-radar.md"
check_pattern "agent-interaction-bridge" "partner/loop-reports/2026-06-07-daily-radar.md"
check_pattern "Nudge Candidate" "partner/loop-reports/2026-06-07-daily-radar.md"
check_pattern "Daily Focus Radar Manual Run" "partner/session-ledger.md"
check_pattern "Third review" "partner/session-ledger.md"
check_pattern "research-loop-packet.md" "partner/session-runbook.md"
check_pattern "loop-report.md" "partner/session-runbook.md"
check_pattern "Project Loop Packet" "partner/templates/project-loop-packet.md"
check_pattern "Research Loop Packet" "partner/templates/research-loop-packet.md"
check_pattern "Thinking Loop Packet" "partner/templates/thinking-loop-packet.md"
check_pattern "Memory Candidate Packet" "partner/templates/memory-candidate-packet.md"
check_pattern "explicitly asks" "partner/templates/memory-candidate-packet.md"
check_pattern "Re-Entry Risk Packet" "partner/templates/reentry-risk-packet.md"
check_pattern "what not to do now" "partner/templates/reentry-risk-packet.md"
check_pattern "Loop Report" "partner/templates/loop-report.md"
check_pattern "Nudge Candidate" "partner/templates/loop-report.md"
check_pattern "needs human decision" "partner/templates/loop-report.md"
check_pattern "Codex Partner Project Pointer" "partner/templates/project-local-pointer.md"
check_pattern "alphaX 介入一下" "partner/templates/project-local-pointer.md"
check_pattern "Project-local instructions" "partner/templates/project-local-pointer.md"
check_pattern "before asking the user to restate context" "partner/templates/project-local-pointer.md"
check_pattern "problem-decomposer" "partner/skills/problem-decomposer/SKILL.md"
check_pattern "D0-D3 decomposition levels" "partner/skills/problem-decomposer/SKILL.md"
check_pattern "Do not confuse" "partner/skills/problem-decomposer/SKILL.md"
check_pattern "Mousetrap Reference" "partner/skills/problem-decomposer/SKILL.md"
check_pattern "problem-decomposer" "partner/activation-guide.md"
check_pattern "problem-decomposer" "partner/decision-log.md"
check_pattern "alphaX" "partner/decision-log.md"
check_pattern "After Two Real Cold Starts" "partner/decision-log.md"
check_pattern "Add Focus And Risk Loop" "partner/decision-log.md"
check_pattern "Borrow Loop Pattern" "partner/decision-log.md"
check_pattern "manual-trigger loops" "partner/decision-log.md"
check_pattern "proactive nudge" "partner/decision-log.md"
check_pattern "Repository Identity Is alpha-partner" "partner/decision-log.md"
check_pattern "Partner Pointer" "scripts/context-snapshot.sh"
check_pattern "project-local-pointer.md" "scripts/context-snapshot.sh"

printf 'Partner workspace verification passed: %s\n' "$ROOT"
